### PR TITLE
unit-tests for Nodes

### PR DESCRIPTION
**Pull request by EthanPadden**
`tst_fromFile_nodes_with_x` and `tst_fromFile_nodes_with_y` will fail. In `nodes_with_x.csv`, one of the x values is set to true. This is also in `nodes_with_y.csv`. I am not sure if this is what is causing the fail, and I do not know if this inserted value is there on purpose or not, but if it is removed, these tests should succeed. I did not want to edit files I was not supposed to just in case.

### CODE REVIEW

**Comment by cardinot** [comment]
Hi @EthanPadden 
Apologies for the typos in the data files, they should not have the `true` in the last row. Could you fix them, please?

Also, are you going to complete the tests below in this PR?
``` c++
void TestNodes::tst_fromCmd();
void TestNodes::tst_fromFile_nodes_no_xy();
void TestNodes::tst_saveToFile_with_attrs();
```

**Comment by EthanPadden** [comment]
Will do, sorry I only looked at the functions between the todo markers.

**Comment by EthanPadden** [comment]
Hi Marcos, I fixed those tests. Apologies again, I did not notice the todo markings in the other functions. I am just trying to figure out how do you test whether a set of nodes are of type UNode or DNode?

**Comment by EthanPadden** [comment]
Thank you, where would this function be placed in the code?

**Comment by cardinot** [comment]
> where would this function be placed in the code?

it could be placed in the `private:` section of [tst_nodes.cpp#L56](https://github.com/EthanPadden/evoplex/blob/1eb0936aabd528342b3fce238ce75f2939cdae9f/src/test/tst_nodes.cpp#L56).

```c++
private:
    // checks if all nodes are of the same type
    template <class T>
    bool nodesOfSameType(const Nodes& nodes)
    {
        for (auto const& it : nodes) {
            if (!dynamic_cast<T*>(it.second.get()))
                return false;
        }
        return true;
    }
```

**Pull request merged**
